-- Shared meal plans: shareable links
CREATE TABLE IF NOT EXISTS public.shared_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  share_token text NOT NULL UNIQUE,
  plan_data jsonb NOT NULL DEFAULT '[]'::jsonb,
  plan_title text NOT NULL DEFAULT 'My Meal Plan',
  week_start text,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz
);

-- Enable RLS
ALTER TABLE public.shared_plans ENABLE ROW LEVEL SECURITY;

-- Owner can manage their own shared plans
CREATE POLICY shared_plans_owner_select ON public.shared_plans
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY shared_plans_owner_insert ON public.shared_plans
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY shared_plans_owner_delete ON public.shared_plans
  FOR DELETE USING (auth.uid() = user_id);

-- Public read access via share_token (for viewing shared plans)
-- We use a permissive SELECT policy that allows reading if the row has a share_token
-- The API route will validate the token before returning data
CREATE POLICY shared_plans_public_read ON public.shared_plans
  FOR SELECT USING (true);

CREATE INDEX shared_plans_share_token_idx ON public.shared_plans(share_token);
CREATE INDEX shared_plans_user_id_idx ON public.shared_plans(user_id);

COMMENT ON TABLE public.shared_plans IS
  'Shared meal plan links generated by users for sharing with others.';
